"""followers

Revision ID: 800421bb934a
Revises: 77aaeaeec307
Create Date: 2021-01-27 14:08:38.061864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800421bb934a'
down_revision = '77aaeaeec307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
